name: Pull Request
description: Submit a pull request for review
title: "[Feature/Fix]: Brief description"
labels: ["needs-review"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for contributing! Please fill out the form below to help us review your changes.

  - type: textarea
    id: description
    attributes:
      label: Description
      description: Provide a brief description of the changes in this PR
      placeholder: What does this PR do?
    validations:
      required: true

  - type: dropdown
    id: change-type
    attributes:
      label: Type of Change
      description: What type of change is this?
      options:
        - Bug fix (non-breaking change that fixes an issue)
        - New feature (non-breaking change that adds functionality)
        - Breaking change (fix or feature that would cause existing functionality to not work as expected)
        - Documentation update
        - Code refactoring
        - Performance improvement
        - Other
    validations:
      required: true

  - type: textarea
    id: changes-made
    attributes:
      label: Changes Made
      description: List the specific changes made in this PR
      placeholder: |
        - Change 1
        - Change 2
        - Change 3
    validations:
      required: true

  - type: input
    id: related-issues
    attributes:
      label: Related Issues
      description: Link any related issues (e.g., "Fixes #123, Related to #456")
      placeholder: "Fixes #123"

  - type: checkboxes
    id: testing
    attributes:
      label: Testing
      description: What testing have you done?
      options:
        - label: Unit tests pass
        - label: Integration tests pass
        - label: Manual testing completed
        - label: No tests needed

  - type: textarea
    id: test-instructions
    attributes:
      label: Test Instructions
      description: Provide step-by-step instructions for testing these changes
      placeholder: |
        1. Step one
        2. Step two
        3. Step three

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots/Videos
      description: If applicable, add screenshots or videos to help explain your changes

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please check all that apply
      options:
        - label: My code follows the project's style guidelines
          required: true
        - label: I have performed a self-review of my code
          required: true
        - label: I have commented my code, particularly in hard-to-understand areas
        - label: I have made corresponding changes to the documentation
        - label: My changes generate no new warnings
        - label: I have added tests that prove my fix is effective or that my feature works
        - label: New and existing unit tests pass locally with my changes

  - type: textarea
    id: breaking-changes
    attributes:
      label: Breaking Changes
      description: If this is a breaking change, describe what breaks and how to migrate

  - type: textarea
    id: additional-notes
    attributes:
      label: Additional Notes
      description: Add any additional notes, concerns, or context for reviewers
